import * as THREE from 'three';
import './styles.css';

const canvas=document.querySelector('#world'), stats=document.querySelector('#stats'), noticeEl=document.querySelector('#notice');
let scene,camera,renderer,sun,moon,terrain,water,agents=[],settlements=[],seed=1,paused=false,speed=1,year=1,day=1,clock=0,births=0,deaths=0,last=performance.now();
const W=100,N=100,step=W/N,WATER_LEVEL=-.48, MAX={fox:16,sheep:42,chicken:55,human:18}; let heights,wet;
const rng=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
function noise(x,z){const i=Math.floor(x),j=Math.floor(z),f=x-i,g=z-j, h=(a,b)=>{let n=(a*374761393+b*668265263+seed*17)>>>0;n=(n^(n>>>13))*1274126177;return ((n^(n>>>16))>>>0)/4294967295};const u=f*f*(3-2*f),v=g*g*(3-2*g);return THREE.MathUtils.lerp(THREE.MathUtils.lerp(h(i,j),h(i+1,j),u),THREE.MathUtils.lerp(h(i,j+1),h(i+1,j+1),u),v)*2-1}
function fbm(x,z){let s=0,a=.55;for(let k=0;k<5;k++){s+=noise(x,z)*a;x*=2.03;z*=2.03;a*=.5}return s}
function H(x,z){let e=fbm(x*.047,z*.047)*7+fbm(x*.13,z*.13)*2.1; e+=Math.max(0,fbm(x*.018+30,z*.018-20)-.08)*17; const river=Math.abs(Math.sin(x*.055+fbm(x*.025,z*.025)*2.1)+z*.012); if(river<.10)e-=4.3*(1-river/.1); return e}
function cell(x,z){const ix=Math.max(0,Math.min(N,Math.round((x+W/2)/step))),iz=Math.max(0,Math.min(N,Math.round((z+W/2)/step)));return {h:heights[iz*(N+1)+ix],water:wet[iz*(N+1)+ix]}}
function safeLand(x,z){
 for(let dz=-.65;dz<=.65;dz+=.65)for(let dx=-.65;dx<=.65;dx+=.65){const c=cell(x+dx,z+dz);if(c.water||c.h<=WATER_LEVEL+.16||c.h>8)return false}
 return true;
}
function buildTerrain(){heights=new Float32Array((N+1)**2);wet=new Uint8Array((N+1)**2);const geo=new THREE.PlaneGeometry(W,W,N,N);geo.rotateX(-Math.PI/2);let pos=geo.attributes.position;for(let i=0;i<pos.count;i++){let x=pos.getX(i),z=pos.getZ(i),h=H(x,z);heights[i]=h;wet[i]=h<=WATER_LEVEL;pos.setY(i,h)}geo.computeVertexNormals();const col=[];for(let i=0;i<pos.count;i++){let h=heights[i],c=wet[i]?new THREE.Color('#315f68'):h>9?new THREE.Color('#88949a'):h>5?new THREE.Color('#54755e'):h>1?new THREE.Color('#6f9152'):new THREE.Color('#98a867');c.offsetHSL(0,0,(rng()-.5)*.12);col.push(c.r,c.g,c.b)}geo.setAttribute('color',new THREE.Float32BufferAttribute(col,3));terrain=new THREE.Mesh(geo,new THREE.MeshLambertMaterial({vertexColors:true,flatShading:true}));terrain.receiveShadow=true;scene.add(terrain);
 const wgeo=geo.clone();let wp=wgeo.attributes.position;for(let i=0;i<wp.count;i++)wp.setY(i,WATER_LEVEL); water=new THREE.Mesh(wgeo,new THREE.MeshPhongMaterial({color:'#397d91',transparent:true,opacity:.76,flatShading:true,side:THREE.DoubleSide}));scene.add(water);
 // sparse low-poly forest only on land
 const treeGeo=new THREE.ConeGeometry(.55,2.5,5), trunk=new THREE.CylinderGeometry(.11,.14,.7,5), forest=new THREE.Group();for(let i=0;i<390;i++){let x=(rng()-.5)*W,z=(rng()-.5)*W,c=cell(x,z);if(!c.water&&c.h>1&&c.h<7){let t=new THREE.Mesh(treeGeo,new THREE.MeshLambertMaterial({color:rng()>.5?'#315c3e':'#3e6b42',flatShading:true}));t.position.set(x,c.h+1.4,z);t.scale.setScalar(.65+rng()*.7);forest.add(t)}}scene.add(forest);
}
function material(type){return new THREE.MeshLambertMaterial({color:{fox:'#d46b39',sheep:'#e8e2c8',chicken:'#dfbf55',human:'#5982a0'}[type],flatShading:true})}
function makeAgent(type){for(let tries=0;tries<160;tries++){let x=(rng()-.5)*80,z=(rng()-.5)*80,c=cell(x,z);if(safeLand(x,z)){let group=new THREE.Group(), body=new THREE.Mesh(type==='human'?new THREE.CylinderGeometry(.26,.32,.9,5):new THREE.DodecahedronGeometry(type==='sheep'?.48:.34,0),material(type));body.position.y=type==='human'?.65:.35;body.castShadow=true;group.add(body);if(type==='human'){let head=new THREE.Mesh(new THREE.IcosahedronGeometry(.2,1),new THREE.MeshLambertMaterial({color:'#d99a6c'}));head.position.y=1.25;group.add(head)}group.position.set(x,c.h,z);scene.add(group);return {type,p:new THREE.Vector2(x,z),v:new THREE.Vector2(),target:null,age:0,energy:80+rng()*20,thirst:80+rng()*20,cool:20+rng()*30,state:'roaming',mesh:group};}}}
function populate(){['sheep','chicken','fox','human'].forEach(t=>{let n={sheep:26,chicken:34,fox:7,human:7}[t];while(n--)agents.push(makeAgent(t))})}
function valid(a,x,z){let samples=5,prev=cell(a.p.x,a.p.y);for(let i=1;i<=samples;i++){let t=i/samples,c=cell(THREE.MathUtils.lerp(a.p.x,x,t),THREE.MathUtils.lerp(a.p.y,z,t));if(c.water||c.h>10||Math.abs(c.h-prev.h)>1.3)return false;prev=c}return true}
function nearest(a,filter,range=30){let best=null,d=range;for(const b of agents)if(b!==a&&filter(b)){let q=a.p.distanceTo(b.p);if(q<d){d=q;best=b}}return best}
function shore(a){let best=null,d=99;for(let k=0;k<24;k++){let x=a.p.x+(rng()-.5)*32,z=a.p.y+(rng()-.5)*32,c=cell(x,z);if(!c.water){let near=cell(x+step,z).water||cell(x-step,z).water||cell(x,z+step).water||cell(x,z-step).water;if(near&&a.p.distanceToSquared(new THREE.Vector2(x,z))<d){best=new THREE.Vector2(x,z);d=a.p.distanceToSquared(best)}}}return best}
function event(s){noticeEl.textContent=s;noticeEl.style.opacity=1;clearTimeout(event.t);event.t=setTimeout(()=>noticeEl.style.opacity=0,3200)}
function die(a,why){scene.remove(a.mesh);agents.splice(agents.indexOf(a),1);deaths++;event(`${a.type[0].toUpperCase()+a.type.slice(1)} ${why}`)}
function updateAgent(a,dt){a.age+=dt*.035;a.energy-=dt*.32;a.thirst-=dt*.42;a.cool-=dt;let predator=nearest(a,b=>(a.type==='sheep'||a.type==='chicken')&&b.type==='fox',14);let target=null;
 if(predator){target=a.p.clone().sub(predator.p).normalize().multiplyScalar(15).add(a.p);a.state='fleeing'} else if(a.thirst<38){target=shore(a);a.state='seeking water'} else {let prey=nearest(a,b=>(a.type==='fox'&&(b.type==='sheep'||b.type==='chicken'))||(a.type==='human'&&b.type==='chicken'),18);if(prey){target=prey.p;a.state='hunting'} else if(a.type==='human'&&settlements.length){target=settlements.reduce((p,s)=>a.p.distanceTo(s.p)<a.p.distanceTo(p.p)?s:p).p;a.state='homeward'} else {if(!a.target||a.p.distanceTo(a.target)<2)a.target=new THREE.Vector2(a.p.x+(rng()-.5)*20,a.p.y+(rng()-.5)*20);target=a.target;a.state='roaming'}}
 if(target){let desired=target.clone().sub(a.p);if(desired.length()>0){desired.normalize();let cand=a.p.clone().addScaledVector(desired,1.3);if(!valid(a,cand.x,cand.y)){desired.rotateAround(new THREE.Vector2(),(rng()>.5?1:-1)*1.1)}a.v.lerp(desired.multiplyScalar(a.type==='fox'?2.1:1.45),.07);let next=a.p.clone().addScaledVector(a.v,dt);if(valid(a,next.x,next.y))a.p.copy(next)}}
 let c=cell(a.p.x,a.p.y);a.mesh.position.set(a.p.x,c.h,a.p.y);if(a.v.lengthSq()>.01)a.mesh.rotation.y=Math.atan2(a.v.x,a.v.y); if(a.thirst<38&&shore(a)&&a.p.distanceTo(shore(a))<2)a.thirst=Math.min(100,a.thirst+dt*14);
 if((a.type==='sheep'||a.type==='chicken')&&a.energy<75){a.energy=Math.min(100,a.energy+dt*3.5)}let victim=nearest(a,b=>(a.type==='fox'&&(b.type==='sheep'||b.type==='chicken'))||(a.type==='human'&&b.type==='chicken'),1.05);if(victim&&a.state==='hunting'){a.energy=Math.min(100,a.energy+45);die(victim,'was hunted')}
 if(a.energy<=0||a.thirst<=0||a.age>125)die(a,a.energy<=0?'starved':a.thirst<=0?'dehydrated':'died of old age');
}
function settlementsTick(dt){let humans=agents.filter(a=>a.type==='human');for(let h of humans){let near=humans.filter(x=>x!==h&&x.p.distanceTo(h.p)<8);if(near.length>=2&&!settlements.some(s=>s.p.distanceTo(h.p)<12)){h.gather=(h.gather||0)+dt;if(h.gather>15){let g=new THREE.Group(),base=new THREE.Mesh(new THREE.BoxGeometry(2,1.2,1.6),new THREE.MeshLambertMaterial({color:'#8a5a37'})),roof=new THREE.Mesh(new THREE.ConeGeometry(1.5,1.3,4),new THREE.MeshLambertMaterial({color:'#bd7545'}));base.position.y=.6;roof.position.y=1.8;roof.rotation.y=.78;g.add(base,roof);let c=cell(h.p.x,h.p.y);g.position.set(h.p.x,c.h,h.p.y);scene.add(g);settlements.push({p:h.p.clone(),mesh:g});event('A new settlement has formed');h.gather=0}}else h.gather=0}}
function birthsTick(){for(const type of Object.keys(MAX)){let group=agents.filter(a=>a.type===type);if(group.length>=MAX[type])continue;let parent=group.find(a=>a.energy>75&&a.thirst>65&&a.cool<=0&&a.age>10);if(parent&&rng()<.22){let child=makeAgent(type);child.p.copy(parent.p).add(new THREE.Vector2((rng()-.5)*2,(rng()-.5)*2));parent.cool=35;agents.push(child);births++}}}
function setup(){scene=new THREE.Scene();scene.fog=new THREE.Fog('#8eaeae',35,120);camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,250);renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;sun=new THREE.DirectionalLight('#fff0c8',2.2);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun,new THREE.HemisphereLight('#b8d9ef','#304521',1.5));moon=new THREE.DirectionalLight('#9cb8ff',.1);scene.add(moon);buildTerrain();populate();camera.position.set(0,48,58);camera.lookAt(0,0,0)}
let yaw=.6,pitch=.68,dist=72,focus=new THREE.Vector3();const keys={};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')speed=speed===1?3:speed===3?6:1;if(e.key.toLowerCase()==='p')paused=!paused});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let drag=false,px,py;canvas.onpointerdown=e=>{drag=true;px=e.clientX;py=e.clientY};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-px)*.006;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-py)*.004,.25,1.35);px=e.clientX;py=e.clientY}});canvas.onwheel=e=>{dist=THREE.MathUtils.clamp(dist+e.deltaY*.04,28,115)};document.querySelector('#reseed').onclick=()=>{scene.clear();agents=[];settlements=[];births=deaths=0;seed=(Math.random()*1e9)|0;buildTerrain();populate();event('A new world has been seeded')};
function animate(now){requestAnimationFrame(animate);let dt=Math.min(.08,(now-last)/1000)*speed;last=now;if(!paused){clock+=dt;day=Math.floor(clock/18)%30+1;year=Math.floor(clock/(18*30))+1;for(const a of [...agents])updateAgent(a,dt);settlementsTick(dt);if(Math.floor(clock)!==Math.floor(clock-dt))birthsTick()}let phase=(clock%180)/180*Math.PI*2, daylight=Math.max(0,Math.sin(phase)*.85+.15);sun.position.set(Math.cos(phase)*45,Math.sin(phase)*55,25);sun.intensity=daylight*2.2;moon.intensity=(1-daylight)*.7;scene.background=new THREE.Color().setHSL(.56,.38,.12+daylight*.5);scene.fog.color.copy(scene.background);let move=new THREE.Vector3();if(keys.w||keys.arrowup)move.z-=1;if(keys.s||keys.arrowdown)move.z+=1;if(keys.a||keys.arrowleft)move.x-=1;if(keys.d||keys.arrowright)move.x+=1;if(keys.q)yaw+=.018;if(keys.e)yaw-=.018;if(keys.r)dist-=.5;if(keys.f)dist+=.5;if(move.lengthSq())focus.add(move.applyAxisAngle(new THREE.Vector3(0,1,0),yaw).multiplyScalar(.45));focus.x=THREE.MathUtils.clamp(focus.x,-42,42);focus.z=THREE.MathUtils.clamp(focus.z,-42,42);camera.position.set(focus.x+Math.sin(yaw)*Math.cos(pitch)*dist,focus.y+Math.sin(pitch)*dist,focus.z+Math.cos(yaw)*Math.cos(pitch)*dist);camera.lookAt(focus);renderer.setSize(innerWidth,innerHeight,false);stats.innerHTML=`<span>YEAR <b>${year} · DAY ${day}</b></span><span>TIME <b>${paused?'PAUSED':'×'+speed}</b></span><span>FOXES <b>${agents.filter(a=>a.type==='fox').length}</b></span><span>SHEEP <b>${agents.filter(a=>a.type==='sheep').length}</b></span><span>CHICKENS <b>${agents.filter(a=>a.type==='chicken').length}</b></span><span>HUMANS <b>${agents.filter(a=>a.type==='human').length}</b></span><span>SETTLEMENTS <b>${settlements.length}</b></span><span>BIRTHS / DEATHS <b>${births} / ${deaths}</b></span>`;renderer.render(scene,camera)}
setup();addEventListener('resize',()=>camera.aspect=innerWidth/innerHeight,camera.updateProjectionMatrix());requestAnimationFrame(animate);
